const questions = [
  {
    question: "What is the speed of light?",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Explain Newton's first law of motion.",
    subject: "Physics",
    topic: "Mechanics",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Describe the process of photosynthesis.",
    subject: "Biology",
    topic: "Botany",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the Pythagorean theorem?",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Define the term 'ecosystem'.",
    subject: "Biology",
    topic: "Ecology",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Solve the equation: 3x + 5 = 14.",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Explain the concept of natural selection.",
    subject: "Biology",
    topic: "Evolution",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "What is Avogadro's number?",
    subject: "Chemistry",
    topic: "Molecular Chemistry",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Describe the water cycle.",
    subject: "Geography",
    topic: "Environmental Science",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What are the layers of the Earth's atmosphere?",
    subject: "Geography",
    topic: "Physical Geography",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is the chemical formula for salt (Sodium Chloride)?",
    subject: "Chemistry",
    topic: "Chemical Compounds",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Explain the principle of Archimedes’ law.",
    subject: "Physics",
    topic: "Fluid Mechanics",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What causes tides in the oceans?",
    subject: "Geography",
    topic: "Oceanography",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Describe the structure of a typical human cell.",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "What is the capital of France?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Calculate the integral of sin(x) dx.",
    subject: "Mathematics",
    topic: "Calculus",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "What is the significance of the Magna Carta?",
    subject: "History",
    topic: "Medieval Europe",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Identify the main stages of the water cycle.",
    subject: "Environmental Science",
    topic: "Earth's Processes",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question:
      "Discuss the impact of the industrial revolution on European society.",
    subject: "History",
    topic: "Modern History",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "Define and exemplify an algorithm.",
    subject: "Computer Science",
    topic: "Fundamentals",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Explain the process of DNA replication.",
    subject: "Biology",
    topic: "Genetics",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "Describe the basic structure of a neuron.",
    subject: "Biology",
    topic: "Neuroscience",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is the function of mitochondria in cells?",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Define the term 'inflation' in economics.",
    subject: "Economics",
    topic: "Macroeconomics",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Who wrote 'The Republic' and what are its main ideas?",
    subject: "Philosophy",
    topic: "Ancient Philosophy",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "Solve the differential equation dy/dx = x^2.",
    subject: "Mathematics",
    topic: "Differential Equations",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "Explain the concept of supply and demand.",
    subject: "Economics",
    topic: "Microeconomics",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the greenhouse effect?",
    subject: "Environmental Science",
    topic: "Climate Change",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Discuss the causes of World War I.",
    subject: "History",
    topic: "World History",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What are the principles of object-oriented programming?",
    subject: "Computer Science",
    topic: "Programming Concepts",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is the primary function of the Large Hadron Collider?",
    subject: "Physics",
    topic: "Particle Physics",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Describe the key events of the French Revolution.",
    subject: "History",
    topic: "European History",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "What is the role of chlorophyll in plants?",
    subject: "Biology",
    topic: "Botany",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Explain the concept of 'opportunity cost' in economics.",
    subject: "Economics",
    topic: "Microeconomics",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is a black hole and how is it formed?",
    subject: "Astronomy",
    topic: "Cosmology",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Calculate the area of a circle with a radius of 5 units.",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question:
      "Explain the significance of the Berlin Wall during the Cold War.",
    subject: "History",
    topic: "Modern History",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What are enzymes and how do they function?",
    subject: "Biology",
    topic: "Biochemistry",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Discuss the impact of social media on modern communication.",
    subject: "Sociology",
    topic: "Media Studies",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is the theory of relativity?",
    subject: "Physics",
    topic: "Theoretical Physics",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "Identify and explain the three laws of thermodynamics.",
    subject: "Physics",
    topic: "Thermodynamics",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "Discuss the concept of 'Demand and Supply' in market economics.",
    subject: "Economics",
    topic: "Microeconomics",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is the significance of the Treaty of Versailles?",
    subject: "History",
    topic: "World History",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Explain the structure and function of the human heart.",
    subject: "Biology",
    topic: "Human Anatomy",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What are prime numbers and how are they identified?",
    subject: "Mathematics",
    topic: "Number Theory",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Describe the process of mitosis in cell division.",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question:
      "What are the key principles of Classical Conditioning in psychology?",
    subject: "Psychology",
    topic: "Behavioral Psychology",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Define and give examples of renewable energy sources.",
    subject: "Environmental Science",
    topic: "Sustainable Energy",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Explain the impact of globalization on world economies.",
    subject: "Economics",
    topic: "Global Economics",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question:
      "What is the significance of Shakespeare's play 'Hamlet' in English literature?",
    subject: "Literature",
    topic: "English Literature",
    difficulty: "Medium",
    marks: 10,
  },
];

export default questions;
